url: "https://bayarea-writethedocs.org"
title: "Write The Docs: Bay Area"

timezone: America/Los_Angeles

collections_dir: content
collections:
  about:
    permalink: /:collection/:path/
    name: About
    output: true
  events:
    permalink: /:collection/:path/
    name: Events
    output: true
  organizers:
    permalink: /:collection/:path/
    name: Organizers
    output: true

# This informs which event is shown as our "next" event. Use the "id" value from the event in events/events-{year}.yml
event_data: "events-2020"
next_event: "jan-2020-project-night"

# These variables can be used to render these FA (FontAwesome 5 Free) icons throughout the site, without getting the whole thing.
# Syntax: {{ site.icons.<icon_name> }}
icons:
  calendar: "<i class='far fa-calendar-plus'></i>"
  clock: "<i class='far fa-clock'></i>"
  external: "<i class='fal fa-external-link'></i>"
  food: "<i class='fas fa-utensils'></i>"
  github: "<i class='fab fa-github-square'></i>"
  hands-helping: "<i class='fas fa-hands-helping'></i>"
  home: "<i class='fad fa-home'></i>"
  info-circle: "i class='fas fa-info-circle'></i>"
  lightbulb: "<i class='far fa-lightbulb'></i>"
  linkedin: "<i class='fab fa-linkedin'></i>"
  map: "<i class='fas fa-map-marked'></i>"
  twitter: "<i class='fab fa-twitter-square'></i>"